import type { JEEStructure } from "../src/create-qp-page/types_qp";

export const qp3: JEEStructure = {
  id: "JEE2025_3",
  name: "Joint Entrance Examination (Main) - 2025 (Paper 3)",
  total_marks: 300,
  duration: 180,
  section: [
    {
      name: "Physics",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: -1,
          questions: [
            {
              id: "P1",
              type: "mcq",
              question:
                "A car moving with velocity 20 m/s applies brakes and comes to rest in 5 seconds. The acceleration is:",
              options: ["-4 m/s²", "-5 m/s²", "-3 m/s²", "-2 m/s²"],
              answer: 0,
            },
            {
              id: "P2",
              type: "mcq",
              question:
                "Two point charges repel each other with force F. If distance between them is halved, the new force is:",
              options: ["F/4", "F/2", "2F", "4F"],
              answer: 3,
            },
            {
              id: "P3",
              type: "mcq",
              question:
                "A mass attached to spring executes SHM. Its total energy is proportional to:",
              options: [
                "Amplitude",
                "Square of amplitude",
                "Frequency",
                "Square of frequency",
              ],
              answer: 1,
            },
            {
              id: "P4",
              type: "mcq",
              question:
                "A particle has momentum p and kinetic energy K. Its mass is:",
              options: ["p²/2K", "2K/p²", "p/2K", "2Kp"],
              answer: 0,
            },
            {
              id: "P5",
              type: "mcq",
              question:
                "In interference, bright fringes are formed when path difference is:",
              options: ["nλ", "(n+1/2)λ", "nλ/2", "(2n+1)λ/2"],
              answer: 0,
            },
            {
              id: "P6",
              type: "mcq",
              question:
                "The work done in moving a unit positive charge from infinity to a point in electric field is:",
              options: [
                "Electric field",
                "Electric potential",
                "Electric flux",
                "Electric dipole moment",
              ],
              answer: 1,
            },
            {
              id: "P7",
              type: "mcq",
              question:
                "In photoelectric effect, the slope of stopping potential vs frequency graph gives:",
              options: [
                "Work function",
                "Planck's constant/e",
                "Threshold frequency",
                "Maximum kinetic energy",
              ],
              answer: 1,
            },
            {
              id: "P8",
              type: "mcq",
              question:
                "A dielectric is inserted between plates of charged capacitor. The energy stored:",
              options: [
                "Increases",
                "Decreases",
                "Remains same",
                "Becomes zero",
              ],
              answer: 1,
            },
            {
              id: "P9",
              type: "mcq",
              question:
                "The direction of magnetic field due to current carrying wire is given by:",
              options: [
                "Fleming's left hand rule",
                "Fleming's right hand rule",
                "Right hand thumb rule",
                "Lenz's rule",
              ],
              answer: 2,
            },
            {
              id: "P10",
              type: "mcq",
              question: "A projectile has maximum range when fired at angle:",
              options: ["30°", "45°", "60°", "90°"],
              answer: 1,
            },
            {
              id: "P11",
              type: "mcq",
              question: "In AC circuit, power factor is maximum when:",
              options: ["XL > XC", "XL < XC", "XL = XC", "XL = 0"],
              answer: 2,
            },
            {
              id: "P12",
              type: "mcq",
              question: "The SI unit of magnetic flux is:",
              options: ["Tesla", "Weber", "Henry", "Gauss"],
              answer: 1,
            },
            {
              id: "P13",
              type: "mcq",
              question:
                "In which process, work done by gas is maximum for same change in volume:",
              options: ["Isothermal", "Adiabatic", "Isobaric", "Isochoric"],
              answer: 0,
            },
            {
              id: "P14",
              type: "mcq",
              question: "Doppler effect in sound depends on:",
              options: [
                "Frequency only",
                "Velocity of source and observer",
                "Amplitude",
                "Wavelength only",
              ],
              answer: 1,
            },
            {
              id: "P15",
              type: "mcq",
              question: "The gravitational potential energy is zero at:",
              options: [
                "Earth surface",
                "Center of earth",
                "Infinity",
                "Height h above surface",
              ],
              answer: 2,
            },
            {
              id: "P16",
              type: "mcq",
              question: "Compton scattering demonstrates:",
              options: [
                "Wave nature of light",
                "Particle nature of light",
                "Dual nature of light",
                "Polarization of light",
              ],
              answer: 1,
            },
            {
              id: "P17",
              type: "mcq",
              question: "The resistivity of a wire depends on:",
              options: ["Length", "Area", "Material", "Current"],
              answer: 2,
            },
            {
              id: "P18",
              type: "mcq",
              question: "Matter waves are associated with:",
              options: [
                "Only electrons",
                "Only photons",
                "All particles",
                "Only charged particles",
              ],
              answer: 2,
            },
            {
              id: "P19",
              type: "mcq",
              question:
                "Four resistors each of 4Ω are connected to form a square. Equivalent resistance between opposite corners is:",
              options: ["4Ω", "2Ω", "8Ω", "1Ω"],
              answer: 1,
            },
            {
              id: "P20",
              type: "mcq",
              question: "In radioactive decay, the number of nuclei decreases:",
              options: [
                "Linearly",
                "Exponentially",
                "Quadratically",
                "Inversely",
              ],
              answer: 1,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "P21",
              type: "nat",
              question:
                "A particle accelerates from 5 m/s to 15 m/s in 2 seconds. Find the distance covered in meters.",
              start: 18,
              end: 22,
              precision: 0,
            },
            {
              id: "P22",
              type: "nat",
              question:
                "Three capacitors 2μF, 4μF, 6μF in series. Find equivalent capacitance in μF (multiply answer by 12).",
              start: 10,
              end: 14,
              precision: 0,
            },
            {
              id: "P23",
              type: "nat",
              question:
                "A pendulum of length 2.5 m has period T. Find T in seconds. (g = 10 m/s², π = 3.14)",
              start: 3.0,
              end: 3.2,
              precision: 1,
            },
            {
              id: "P24",
              type: "nat",
              question:
                "Find the energy of photon with wavelength 400 nm in eV. (h = 6.6 × 10⁻³⁴ Js, c = 3 × 10⁸ m/s, e = 1.6 × 10⁻¹⁹ C)",
              start: 3.0,
              end: 3.2,
              precision: 1,
            },
            {
              id: "P25",
              type: "nat",
              question:
                "An electron in hydrogen atom jumps from n=4 to n=1. Find the number of possible spectral lines.",
              start: 5,
              end: 7,
              precision: 0,
            },
            {
              id: "P26",
              type: "nat",
              question:
                "A solid sphere of radius 2 m, mass 8 kg. Find moment of inertia about diameter in kg⋅m².",
              start: 12,
              end: 14,
              precision: 0,
            },
            {
              id: "P27",
              type: "nat",
              question:
                "Electric field due to infinite sheet with surface charge density 10⁻⁶ C/m². Find E in N/C. (ε₀ = 8.85 × 10⁻¹²)",
              start: 55000,
              end: 57000,
              precision: 0,
            },
            {
              id: "P28",
              type: "nat",
              question:
                "A converging lens has focal length 25 cm. Object at 50 cm forms image at distance in cm:",
              start: 48,
              end: 52,
              precision: 0,
            },
            {
              id: "P29",
              type: "nat",
              question:
                "A 6V battery with internal resistance 1Ω connected to 5Ω resistor. Find terminal voltage in V.",
              start: 4.8,
              end: 5.2,
              precision: 1,
            },
            {
              id: "P30",
              type: "nat",
              question:
                "A satellite orbits earth at height equal to earth radius. Find orbital speed in terms of escape velocity ve (answer as ve/√n, give n).",
              start: 1,
              end: 3,
              precision: 0,
            },
          ],
        },
      ],
    },
    {
      name: "Chemistry",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: -2,
          questions: [
            {
              id: "C1",
              type: "mcq",
              question: "The shape of PCl₅ molecule is:",
              options: [
                "Tetrahedral",
                "Square pyramidal",
                "Trigonal bipyramidal",
                "Octahedral",
              ],
              answer: 2,
            },
            {
              id: "C2",
              type: "mcq",
              question: "Which of the following has maximum lattice energy?",
              options: ["NaCl", "MgO", "CaF₂", "KBr"],
              answer: 1,
            },
            {
              id: "C3",
              type: "mcq",
              question:
                "The molarity of 20% NaOH solution (density = 1.2 g/mL) is approximately:",
              options: ["4M", "5M", "6M", "7M"],
              answer: 2,
            },
            {
              id: "C4",
              type: "mcq",
              question: "Which of the following is amphoteric?",
              options: ["Al₂O₃", "MgO", "Na₂O", "SO₃"],
              answer: 0,
            },
            {
              id: "C5",
              type: "mcq",
              question: "The conjugate base of HSO₄⁻ is:",
              options: ["H₂SO₄", "SO₄²⁻", "SO₃²⁻", "H₂SO₃"],
              answer: 1,
            },
            {
              id: "C6",
              type: "mcq",
              question:
                "In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, the reducing agent is:",
              options: ["Zn", "Cu²⁺", "SO₄²⁻", "Cu"],
              answer: 0,
            },
            {
              id: "C7",
              type: "mcq",
              question: "Acetylene on polymerization gives:",
              options: ["Benzene", "Cyclohexane", "Toluene", "Phenol"],
              answer: 0,
            },
            {
              id: "C8",
              type: "mcq",
              question:
                "Which compound shows both aldol condensation and Cannizzaro reaction?",
              options: ["CH₃CHO", "HCHO", "C₆H₅CHO", "(CH₃)₂CHCHO"],
              answer: 2,
            },
            {
              id: "C9",
              type: "mcq",
              question: "Lucas reagent is used to distinguish between:",
              options: [
                "Primary, secondary, tertiary alcohols",
                "Aldehydes and ketones",
                "Alkenes and alkynes",
                "Carboxylic acids and esters",
              ],
              answer: 0,
            },
            {
              id: "C10",
              type: "mcq",
              question: "The hybridization of carbon atoms in C₂H₄ is:",
              options: ["sp³", "sp²", "sp", "sp³d"],
              answer: 1,
            },
            {
              id: "C11",
              type: "mcq",
              question: "Which has maximum electron affinity?",
              options: ["F", "Cl", "Br", "I"],
              answer: 1,
            },
            {
              id: "C12",
              type: "mcq",
              question: "The bond angle in water molecule is approximately:",
              options: ["90°", "104.5°", "109.5°", "120°"],
              answer: 1,
            },
            {
              id: "C13",
              type: "mcq",
              question:
                "For a zero order reaction, the rate constant has units:",
              options: ["mol L⁻¹ s⁻¹", "s⁻¹", "mol⁻¹ L s⁻¹", "mol⁻² L² s⁻¹"],
              answer: 0,
            },
            {
              id: "C14",
              type: "mcq",
              question: "Bakelite is formed by condensation polymerization of:",
              options: [
                "Phenol and formaldehyde",
                "Ethylene glycol and terephthalic acid",
                "Hexamethylene diamine and adipic acid",
                "Styrene",
              ],
              answer: 0,
            },
            {
              id: "C15",
              type: "mcq",
              question: "The IUPAC name of [Co(NH₃)₆]Cl₃ is:",
              options: [
                "Hexaamminecobalt(III) chloride",
                "Cobalt hexaammine trichloride",
                "Trichlorohexaamminecobalt",
                "Hexaamminecobalt trichloride",
              ],
              answer: 0,
            },
            {
              id: "C16",
              type: "mcq",
              question: "Which of the following is aromatic?",
              options: [
                "Cyclobutadiene",
                "Benzene",
                "Cyclooctatetraene",
                "Cyclohexene",
              ],
              answer: 1,
            },
            {
              id: "C17",
              type: "mcq",
              question: "The elevation in boiling point is maximum for:",
              options: [
                "0.1 M glucose",
                "0.1 M NaCl",
                "0.1 M BaCl₂",
                "0.1 M Al₂(SO₄)₃",
              ],
              answer: 3,
            },
            {
              id: "C18",
              type: "mcq",
              question: "For spontaneous reaction, ΔG should be:",
              options: ["Positive", "Negative", "Zero", "Infinite"],
              answer: 1,
            },
            {
              id: "C19",
              type: "mcq",
              question: "Marsh test is used for detection of:",
              options: ["Phosphorus", "Arsenic", "Antimony", "Bismuth"],
              answer: 1,
            },
            {
              id: "C20",
              type: "mcq",
              question: "Vulcanization of rubber involves:",
              options: [
                "Addition of sulfur",
                "Oxidation",
                "Reduction",
                "Hydrolysis",
              ],
              answer: 0,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "C21",
              type: "nat",
              question:
                "Find the number of moles in 22g CO₂. (Molecular mass = 44)",
              start: 0.4,
              end: 0.6,
              precision: 1,
            },
            {
              id: "C22",
              type: "nat",
              question: "Calculate pOH of 0.1 M NaOH solution.",
              start: 0.8,
              end: 1.2,
              precision: 1,
            },
            {
              id: "C23",
              type: "nat",
              question: "How many protons are in nucleus of ²³⁹Pu?",
              start: 92,
              end: 96,
              precision: 0,
            },
            {
              id: "C24",
              type: "nat",
              question: "The number of optical isomers of CHBrClF is:",
              start: 1,
              end: 3,
              precision: 0,
            },
            {
              id: "C25",
              type: "nat",
              question:
                "At 27°C, what is the RMS velocity of H₂ in m/s? (R = 8.314 J/mol⋅K)",
              start: 1920,
              end: 1940,
              precision: 0,
            },
            {
              id: "C26",
              type: "nat",
              question: "Find the oxidation state of chlorine in ClO₄⁻.",
              start: 6,
              end: 8,
              precision: 0,
            },
            {
              id: "C27",
              type: "nat",
              question: "How many lone pairs are present in NH₃?",
              start: 0,
              end: 2,
              precision: 0,
            },
            {
              id: "C28",
              type: "nat",
              question:
                "The pH of mixture of 100 mL 0.1M HCl and 100 mL 0.1M NaOH is:",
              start: 6,
              end: 8,
              precision: 0,
            },
            {
              id: "C29",
              type: "nat",
              question:
                "The spin-only magnetic moment of Mn²⁺ in Bohr magnetons is:",
              start: 5.5,
              end: 6.0,
              precision: 1,
            },
            {
              id: "C30",
              type: "nat",
              question: "How many bridging CO ligands are present in Co₂(CO)₈?",
              start: 1,
              end: 3,
              precision: 0,
            },
          ],
        },
      ],
    },
    {
      name: "Mathematics",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "M1",
              type: "mcq",
              question: "If tan θ = 1, then θ in [0, π] is:",
              options: ["π/6", "π/4", "π/3", "π/2"],
              answer: 1,
            },
            {
              id: "M2",
              type: "mcq",
              question: "The derivative of ln(x) is:",
              options: ["1", "1/x", "ln(x)", "x"],
              answer: 1,
            },
            {
              id: "M3",
              type: "mcq",
              question: "The integral of cos(x) dx is:",
              options: [
                "-sin(x) + C",
                "sin(x) + C",
                "cos(x) + C",
                "-cos(x) + C",
              ],
              answer: 1,
            },
            {
              id: "M4",
              type: "mcq",
              question:
                "If n(A ∪ B) = 50, n(A) = 30, n(B) = 35, then n(A ∩ B) is:",
              options: ["15", "20", "25", "10"],
              answer: 0,
            },
            {
              id: "M5",
              type: "mcq",
              question:
                "The equation of line with x-intercept 4 and y-intercept 3 is:",
              options: [
                "3x + 4y = 12",
                "4x + 3y = 12",
                "x/4 + y/3 = 1",
                "Both A and C",
              ],
              answer: 3,
            },
            {
              id: "M6",
              type: "mcq",
              question: "The coefficient of x⁴ in (1 + x)⁸ is:",
              options: ["56", "70", "84", "120"],
              answer: 1,
            },
            {
              id: "M7",
              type: "mcq",
              question: "If α and β are roots of x² + 5x + 6 = 0, then αβ is:",
              options: ["5", "-5", "6", "-6"],
              answer: 2,
            },
            {
              id: "M8",
              type: "mcq",
              question:
                "The equation of circle with center (2, 3) and radius 5 is:",
              options: [
                "(x-2)² + (y-3)² = 25",
                "(x+2)² + (y+3)² = 25",
                "(x-2)² + (y-3)² = 5",
                "x² + y² = 25",
              ],
              answer: 0,
            },
            {
              id: "M9",
              type: "mcq",
              question: "If 2^x = 32, then x is:",
              options: ["4", "5", "6", "16"],
              answer: 1,
            },
            {
              id: "M10",
              type: "mcq",
              question: "If f(x) = x³ - 1, then f⁻¹(7) is:",
              options: ["2", "3", "4", "8"],
              answer: 0,
            },
            {
              id: "M11",
              type: "mcq",
              question: "The nth term of AP: 7, 10, 13, 16, ... is:",
              options: ["3n + 4", "3n + 7", "4n + 3", "7n + 3"],
              answer: 0,
            },
            {
              id: "M12",
              type: "mcq",
              question:
                "The centroid of triangle with vertices (0,0), (6,0), and (0,9) is:",
              options: ["(2,3)", "(3,3)", "(2,4)", "(3,2)"],
              answer: 0,
            },
            {
              id: "M13",
              type: "mcq",
              question: "If z₁ = 1+2i and z₂ = 2-i, then z₁z₂ is:",
              options: ["4-3i", "4+3i", "3+4i", "3-4i"],
              answer: 1,
            },
            {
              id: "M14",
              type: "mcq",
              question: "The constant term in expansion of (x + 1/x)⁶ is:",
              options: ["15", "20", "10", "6"],
              answer: 1,
            },
            {
              id: "M15",
              type: "mcq",
              question: "The period of tan(x) is:",
              options: ["π/2", "π", "2π", "π/4"],
              answer: 1,
            },
            {
              id: "M16",
              type: "mcq",
              question: "If A = [1 2; 3 4], then det(A) is:",
              options: ["-2", "2", "10", "-1"],
              answer: 0,
            },
            {
              id: "M17",
              type: "mcq",
              question: "The directrix of parabola y² = 8x is:",
              options: ["x = -2", "x = 2", "y = -2", "y = 2"],
              answer: 0,
            },
            {
              id: "M18",
              type: "mcq",
              question:
                "A bag contains 3 red and 4 blue balls. Probability of drawing a red ball is:",
              options: ["3/7", "4/7", "3/4", "1/2"],
              answer: 0,
            },
            {
              id: "M19",
              type: "mcq",
              question: "The value of ∫₁² (2x+1) dx is:",
              options: ["5", "6", "7", "8"],
              answer: 2,
            },
            {
              id: "M20",
              type: "mcq",
              question: "If a⃗ = î + ĵ and b⃗ = î - ĵ, then a⃗ × b⃗ is:",
              options: ["0", "2k̂", "-2k̂", "î + ĵ"],
              answer: 2,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "M21",
              type: "nat",
              question: "Find the value of 5² + 4² - 3².",
              start: 30,
              end: 34,
              precision: 0,
            },
            {
              id: "M22",
              type: "nat",
              question: "If p(x) = 2x³ - x² + 3x - 1, find p(2).",
              start: 15,
              end: 19,
              precision: 0,
            },
            {
              id: "M23",
              type: "nat",
              question: "In how many ways can 6 people sit in a row?",
              start: 715,
              end: 725,
              precision: 0,
            },
            {
              id: "M24",
              type: "nat",
              question:
                "Find the area of rectangle with length 12 cm and breadth 8 cm.",
              start: 94,
              end: 98,
              precision: 0,
            },
            {
              id: "M25",
              type: "nat",
              question:
                "If log₁₀ 5 = 0.699, find log₁₀ 125 (answer as integer after multiplying by 1000).",
              start: 2095,
              end: 2105,
              precision: 0,
            },
            {
              id: "M26",
              type: "nat",
              question: "Find the sum to infinity of GP: 1, 1/2, 1/4, 1/8, ...",
              start: 1.8,
              end: 2.2,
              precision: 1,
            },
            {
              id: "M27",
              type: "nat",
              question:
                "If cos θ = 12/13, find sin θ (considering θ in first quadrant).",
              start: 4,
              end: 6,
              precision: 0,
            },
            {
              id: "M28",
              type: "nat",
              question:
                "Find the sum of interior angles of a decagon in degrees.",
              start: 1440,
              end: 1440,
              precision: 0,
            },
            {
              id: "M29",
              type: "nat",
              question: "The mode of data: 2, 3, 4, 4, 5, 5, 5, 6 is:",
              start: 4,
              end: 6,
              precision: 0,
            },
            {
              id: "M30",
              type: "nat",
              question: "Find the value of ⁸C₄.",
              start: 68,
              end: 72,
              precision: 0,
            },
          ],
        },
      ],
    },
  ],
};
