import type { JEEStructure } from "../src/create-qp-page/types_qp";

// Question Paper 4
export const qp4: JEEStructure = {
  id: "JEE2025_4",
  name: "Joint Entrance Examination (Main) - 2025 (Paper 4)",
  total_marks: 300,
  duration: 180,
  section: [
    {
      name: "Physics",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: -1,
          questions: [
            {
              id: "P1",
              type: "mcq",
              question:
                "A body starts from rest and moves with constant acceleration. The ratio of distances in successive seconds is:",
              options: ["1:2:3", "1:3:5", "1:4:7", "2:3:4"],
              answer: 1,
            },
            {
              id: "P2",
              type: "mcq",
              question:
                "The electric field inside a conductor in electrostatic equilibrium is:",
              options: ["Maximum", "Minimum", "Zero", "Variable"],
              answer: 2,
            },
            {
              id: "P3",
              type: "mcq",
              question:
                "For a particle executing SHM, the acceleration is maximum when:",
              options: [
                "Velocity is maximum",
                "Displacement is maximum",
                "At equilibrium position",
                "At any position",
              ],
              answer: 1,
            },
            {
              id: "P4",
              type: "mcq",
              question:
                "If kinetic energy of a body is increased by 300%, its momentum increases by:",
              options: ["100%", "200%", "300%", "400%"],
              answer: 0,
            },
            {
              id: "P5",
              type: "mcq",
              question:
                "In diffraction grating, for maximum intensity, the path difference should be:",
              options: ["nλ", "(n+1/2)λ", "nλ/2", "(2n+1)λ/4"],
              answer: 0,
            },
            {
              id: "P6",
              type: "mcq",
              question:
                "The electric field lines around an isolated positive charge are:",
              options: [
                "Circular",
                "Radially inward",
                "Radially outward",
                "Parallel",
              ],
              answer: 2,
            },
            {
              id: "P7",
              type: "mcq",
              question: "The photoelectric effect was explained by:",
              options: ["Newton", "Maxwell", "Einstein", "Planck"],
              answer: 2,
            },
            {
              id: "P8",
              type: "mcq",
              question:
                "When two identical capacitors are connected in series, the equivalent capacitance is:",
              options: ["C", "C/2", "2C", "4C"],
              answer: 1,
            },
            {
              id: "P9",
              type: "mcq",
              question:
                "The magnetic field at a point on the axis of a circular current loop is:",
              options: ["Maximum", "Zero", "Less than at center", "Infinite"],
              answer: 2,
            },
            {
              id: "P10",
              type: "mcq",
              question: "For projectile motion, the trajectory is:",
              options: ["Straight line", "Circle", "Parabola", "Ellipse"],
              answer: 2,
            },
            {
              id: "P11",
              type: "mcq",
              question: "In RLC circuit, resonance occurs when:",
              options: ["XL = XC", "XL > XC", "XL < XC", "R = 0"],
              answer: 0,
            },
            {
              id: "P12",
              type: "mcq",
              question: "The unit of coefficient of self-induction is:",
              options: ["Weber", "Tesla", "Henry", "Volt"],
              answer: 2,
            },
            {
              id: "P13",
              type: "mcq",
              question:
                "In which thermodynamic process, temperature remains constant:",
              options: ["Adiabatic", "Isothermal", "Isobaric", "Isochoric"],
              answer: 1,
            },
            {
              id: "P14",
              type: "mcq",
              question: "The speed of sound in air at 0°C is approximately:",
              options: ["300 m/s", "330 m/s", "340 m/s", "350 m/s"],
              answer: 1,
            },
            {
              id: "P15",
              type: "mcq",
              question: "The acceleration due to gravity decreases with:",
              options: [
                "Increase in height",
                "Decrease in height",
                "Increase in mass",
                "Decrease in mass",
              ],
              answer: 0,
            },
            {
              id: "P16",
              type: "mcq",
              question: "Beta rays are:",
              options: ["Electrons", "Protons", "Neutrons", "Alpha particles"],
              answer: 0,
            },
            {
              id: "P17",
              type: "mcq",
              question:
                "The drift velocity of electrons in a conductor is of the order of:",
              options: ["10⁸ m/s", "10⁶ m/s", "10⁻³ m/s", "10⁻⁶ m/s"],
              answer: 2,
            },
            {
              id: "P18",
              type: "mcq",
              question: "The rest mass of photon is:",
              options: [
                "Very small",
                "Equal to electron mass",
                "Infinite",
                "Zero",
              ],
              answer: 3,
            },
            {
              id: "P19",
              type: "mcq",
              question:
                "Five resistors each of 10Ω are connected in parallel. The equivalent resistance is:",
              options: ["50Ω", "10Ω", "5Ω", "2Ω"],
              answer: 3,
            },
            {
              id: "P20",
              type: "mcq",
              question:
                "Half-life of a radioactive element is the time in which:",
              options: [
                "All nuclei decay",
                "Half nuclei decay",
                "1/4 nuclei decay",
                "3/4 nuclei decay",
              ],
              answer: 1,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "P21",
              type: "nat",
              question:
                "A ball is dropped from height 80 m. Find time to reach ground in seconds. (g = 10 m/s²)",
              start: 3.8,
              end: 4.2,
              precision: 1,
            },
            {
              id: "P22",
              type: "nat",
              question:
                "Two capacitors 6μF and 3μF in parallel. Find total capacitance in μF.",
              start: 8,
              end: 10,
              precision: 0,
            },
            {
              id: "P23",
              type: "nat",
              question:
                "A body of mass 4 kg has frequency 0.5 Hz. Find spring constant in N/m. (π² = 10)",
              start: 38,
              end: 42,
              precision: 0,
            },
            {
              id: "P24",
              type: "nat",
              question:
                "Find momentum of photon with energy 4 eV in kg⋅m/s. (c = 3 × 10⁸ m/s, 1 eV = 1.6 × 10⁻¹⁹ J) Answer in 10⁻²⁷ units.",
              start: 2.0,
              end: 2.4,
              precision: 1,
            },
            {
              id: "P25",
              type: "nat",
              question:
                "In hydrogen spectrum, Balmer series corresponds to transitions ending at n = ?",
              start: 1,
              end: 3,
              precision: 0,
            },
            {
              id: "P26",
              type: "nat",
              question:
                "A hollow cylinder of radius 3 m, mass 6 kg. Find moment of inertia about axis in kg⋅m².",
              start: 52,
              end: 56,
              precision: 0,
            },
            {
              id: "P27",
              type: "nat",
              question:
                "Electric potential at distance 2 m from 8μC charge in air. Find V in volts. (k = 9 × 10⁹)",
              start: 35000,
              end: 37000,
              precision: 0,
            },
            {
              id: "P28",
              type: "nat",
              question:
                "A diverging lens has focal length -20 cm. Object at 60 cm forms image at distance in cm (magnitude):",
              start: 14,
              end: 16,
              precision: 0,
            },
            {
              id: "P29",
              type: "nat",
              question:
                "Three resistors 3Ω, 6Ω, 9Ω in series with 18V battery. Find current in A.",
              start: 0.8,
              end: 1.2,
              precision: 1,
            },
            {
              id: "P30",
              type: "nat",
              question:
                "A body moves in circle of radius 5 m with period 10 s. Find centripetal acceleration in m/s².",
              start: 1.8,
              end: 2.2,
              precision: 1,
            },
          ],
        },
      ],
    },
    {
      name: "Chemistry",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: -2,
          questions: [
            {
              id: "C1",
              type: "mcq",
              question: "The number of unpaired electrons in Cu²⁺ is:",
              options: ["0", "1", "2", "3"],
              answer: 1,
            },
            {
              id: "C2",
              type: "mcq",
              question: "Which of the following has minimum ionization energy?",
              options: ["Li", "Be", "B", "C"],
              answer: 0,
            },
            {
              id: "C3",
              type: "mcq",
              question: "The normality of 0.5 M H₂SO₄ solution is:",
              options: ["0.5 N", "1.0 N", "1.5 N", "2.0 N"],
              answer: 1,
            },
            {
              id: "C4",
              type: "mcq",
              question: "The Kw of water at 25°C is:",
              options: ["1 × 10⁻¹²", "1 × 10⁻¹⁴", "1 × 10⁻¹⁶", "1 × 10⁻⁷"],
              answer: 1,
            },
            {
              id: "C5",
              type: "mcq",
              question: "According to Lewis theory, a base is:",
              options: [
                "Proton donor",
                "Proton acceptor",
                "Electron donor",
                "Electron acceptor",
              ],
              answer: 2,
            },
            {
              id: "C6",
              type: "mcq",
              question:
                "In the reaction 2FeCl₃ + SnCl₂ → 2FeCl₂ + SnCl₄, the oxidizing agent is:",
              options: ["FeCl₃", "SnCl₂", "FeCl₂", "SnCl₄"],
              answer: 0,
            },
            {
              id: "C7",
              type: "mcq",
              question: "Friedel-Crafts reaction is used for:",
              options: [
                "Nitration",
                "Sulfonation",
                "Alkylation",
                "Halogenation",
              ],
              answer: 2,
            },
            {
              id: "C8",
              type: "mcq",
              question: "Grignard reagent reacts with water to give:",
              options: ["Alcohol", "Alkane", "Aldehyde", "Ketone"],
              answer: 1,
            },
            {
              id: "C9",
              type: "mcq",
              question: "Fehling reagent is used to test for:",
              options: ["Aldehydes", "Ketones", "Alcohols", "Ethers"],
              answer: 0,
            },
            {
              id: "C10",
              type: "mcq",
              question: "The bond order of O₂ molecule is:",
              options: ["1", "1.5", "2", "2.5"],
              answer: 2,
            },
            {
              id: "C11",
              type: "mcq",
              question: "The first ionization energy is highest for:",
              options: ["F", "Ne", "Na", "Mg"],
              answer: 1,
            },
            {
              id: "C12",
              type: "mcq",
              question: "The bond angle in methane is:",
              options: ["90°", "104.5°", "109.5°", "120°"],
              answer: 2,
            },
            {
              id: "C13",
              type: "mcq",
              question:
                "The order of reaction with respect to A in rate = k[A]²[B] is:",
              options: ["1", "2", "3", "0"],
              answer: 1,
            },
            {
              id: "C14",
              type: "mcq",
              question: "PVC is a polymer of:",
              options: ["Vinyl chloride", "Ethylene", "Propylene", "Styrene"],
              answer: 0,
            },
            {
              id: "C15",
              type: "mcq",
              question: "The oxidation number of iron in K₄[Fe(CN)₆] is:",
              options: ["+1", "+2", "+3", "+4"],
              answer: 1,
            },
            {
              id: "C16",
              type: "mcq",
              question: "Huckel rule for aromaticity requires:",
              options: [
                "4n electrons",
                "4n+2 electrons",
                "2n electrons",
                "6n electrons",
              ],
              answer: 1,
            },
            {
              id: "C17",
              type: "mcq",
              question: "The osmotic pressure is maximum for:",
              options: [
                "0.1 M glucose",
                "0.1 M KCl",
                "0.1 M MgCl₂",
                "0.1 M AlCl₃",
              ],
              answer: 3,
            },
            {
              id: "C18",
              type: "mcq",
              question: "A reaction is spontaneous when:",
              options: ["ΔH < 0", "ΔS > 0", "ΔG < 0", "ΔG > 0"],
              answer: 2,
            },
            {
              id: "C19",
              type: "mcq",
              question: "Baeyer test is used for:",
              options: ["Alkanes", "Alkenes", "Alkynes", "Aromatics"],
              answer: 1,
            },
            {
              id: "C20",
              type: "mcq",
              question: "Natural gas mainly contains:",
              options: ["Ethane", "Propane", "Methane", "Butane"],
              answer: 2,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "C21",
              type: "nat",
              question:
                "Find the molecular weight of Ca(OH)₂. (Ca=40, O=16, H=1)",
              start: 72,
              end: 76,
              precision: 0,
            },
            {
              id: "C22",
              type: "nat",
              question: "Calculate the pH of 0.001 M HCl solution.",
              start: 2.8,
              end: 3.2,
              precision: 1,
            },
            {
              id: "C23",
              type: "nat",
              question: "How many electrons are present in Al³⁺ ion?",
              start: 8,
              end: 12,
              precision: 0,
            },
            {
              id: "C24",
              type: "nat",
              question: "The number of sigma bonds in ethyne (C₂H₂) is:",
              start: 2,
              end: 4,
              precision: 0,
            },
            {
              id: "C25",
              type: "nat",
              question:
                "Find the density of CO₂ at STP in g/L. (Molecular mass = 44)",
              start: 1.8,
              end: 2.2,
              precision: 1,
            },
            {
              id: "C26",
              type: "nat",
              question:
                "Find the oxidation number of nitrogen in NH₄NO₃ (average).",
              start: -1,
              end: 1,
              precision: 0,
            },
            {
              id: "C27",
              type: "nat",
              question: "How many double bonds are present in benzene?",
              start: 2,
              end: 4,
              precision: 0,
            },
            {
              id: "C28",
              type: "nat",
              question:
                "What is the molarity of solution containing 49g H₂SO₄ in 500 mL solution? (Molecular mass = 98)",
              start: 0.8,
              end: 1.2,
              precision: 1,
            },
            {
              id: "C29",
              type: "nat",
              question: "The number of d-electrons in Fe²⁺ is:",
              start: 5,
              end: 7,
              precision: 0,
            },
            {
              id: "C30",
              type: "nat",
              question: "How many isomers are possible for C₄H₈?",
              start: 4,
              end: 6,
              precision: 0,
            },
          ],
        },
      ],
    },
    {
      name: "Mathematics",
      totalmarks: 100,
      totalquestion: 30,
      weightage: [
        {
          type: "mcq",
          count: 20,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "M1",
              type: "mcq",
              question: "If sec θ = 2, then cos θ is:",
              options: ["1/2", "2", "-1/2", "±1/2"],
              answer: 0,
            },
            {
              id: "M2",
              type: "mcq",
              question: "The derivative of tan(x) is:",
              options: ["sec²(x)", "sec(x)tan(x)", "cot²(x)", "cosec²(x)"],
              answer: 0,
            },
            {
              id: "M3",
              type: "mcq",
              question: "The integral of sec²(x) dx is:",
              options: [
                "tan(x) + C",
                "sec(x) + C",
                "cot(x) + C",
                "cosec(x) + C",
              ],
              answer: 0,
            },
            {
              id: "M4",
              type: "mcq",
              question: "If A - B = {1, 3} and A = {1, 2, 3, 4}, then B is:",
              options: ["{2, 4}", "{1, 3}", "{2, 3, 4}", "{1, 2, 4}"],
              answer: 0,
            },
            {
              id: "M5",
              type: "mcq",
              question: "The lines 2x + 3y = 6 and 4x + 6y = 12 are:",
              options: [
                "Parallel",
                "Perpendicular",
                "Intersecting",
                "Coincident",
              ],
              answer: 3,
            },
            {
              id: "M6",
              type: "mcq",
              question: "The term independent of x in (x + 1/x²)⁹ is:",
              options: ["⁹C₃", "⁹C₆", "⁹C₄", "⁹C₅"],
              answer: 0,
            },
            {
              id: "M7",
              type: "mcq",
              question: "The discriminant of x² - 4x + 4 is:",
              options: ["0", "4", "8", "16"],
              answer: 0,
            },
            {
              id: "M8",
              type: "mcq",
              question: "The focus of parabola x² = 4y is:",
              options: ["(0, 1)", "(1, 0)", "(0, -1)", "(-1, 0)"],
              answer: 0,
            },
            {
              id: "M9",
              type: "mcq",
              question: "If log₂ (x-1) = 3, then x is:",
              options: ["7", "8", "9", "10"],
              answer: 2,
            },
            {
              id: "M10",
              type: "mcq",
              question: "The domain of f(x) = √(x-2) is:",
              options: ["x ≥ 2", "x ≤ 2", "x > 2", "All real numbers"],
              answer: 0,
            },
            {
              id: "M11",
              type: "mcq",
              question:
                "The sum of first 10 terms of GP: 2, 6, 18, 54, ... is:",
              options: ["59048", "59049", "59050", "59051"],
              answer: 0,
            },
            {
              id: "M12",
              type: "mcq",
              question: "The slope of line joining (3, 4) and (7, 8) is:",
              options: ["1", "2", "1/2", "4"],
              answer: 0,
            },
            {
              id: "M13",
              type: "mcq",
              question: "If |z - 2| = 3, then z lies on:",
              options: ["Circle", "Ellipse", "Parabola", "Hyperbola"],
              answer: 0,
            },
            {
              id: "M14",
              type: "mcq",
              question: "The greatest coefficient in (1 + x)¹⁰ is:",
              options: ["¹⁰C₄", "¹⁰C₅", "¹⁰C₆", "¹⁰C₁₀"],
              answer: 1,
            },
            {
              id: "M15",
              type: "mcq",
              question: "The minimum value of sin²x + cos²x is:",
              options: ["0", "1", "2", "-1"],
              answer: 1,
            },
            {
              id: "M16",
              type: "mcq",
              question: "If A is 2×2 matrix with |A| = 3, then |2A| is:",
              options: ["6", "9", "12", "18"],
              answer: 2,
            },
            {
              id: "M17",
              type: "mcq",
              question: "The eccentricity of circle is:",
              options: ["0", "1", "√2", "∞"],
              answer: 0,
            },
            {
              id: "M18",
              type: "mcq",
              question:
                "Three coins are tossed. Probability of getting at least one head is:",
              options: ["7/8", "1/8", "3/8", "5/8"],
              answer: 0,
            },
            {
              id: "M19",
              type: "mcq",
              question: "The value of ∫₀^(π/2) sin x dx is:",
              options: ["0", "1", "2", "π/2"],
              answer: 1,
            },
            {
              id: "M20",
              type: "mcq",
              question: "The unit vectors along x, y, z axes are:",
              options: ["î, ĵ, k̂", "x̂, ŷ, ẑ", "1, 1, 1", "All of these"],
              answer: 0,
            },
          ],
        },
        {
          type: "nat",
          count: 10,
          attempt: 5,
          marks: 4,
          positive: 4,
          negative: 0,
          questions: [
            {
              id: "M21",
              type: "nat",
              question: "Find the value of 6! / 4!.",
              start: 28,
              end: 32,
              precision: 0,
            },
            {
              id: "M22",
              type: "nat",
              question: "If r(x) = x⁴ - 3x² + 2, find r(1).",
              start: -1,
              end: 1,
              precision: 0,
            },
            {
              id: "M23",
              type: "nat",
              question:
                "How many 3-digit numbers can be formed using digits 1, 2, 3, 4, 5 without repetition?",
              start: 58,
              end: 62,
              precision: 0,
            },
            {
              id: "M24",
              type: "nat",
              question: "Find the perimeter of square with side 7 cm.",
              start: 26,
              end: 30,
              precision: 0,
            },
            {
              id: "M25",
              type: "nat",
              question:
                "If log₁₀ 7 = 0.845, find log₁₀ 49 (answer as integer after multiplying by 1000).",
              start: 1690,
              end: 1695,
              precision: 0,
            },
            {
              id: "M26",
              type: "nat",
              question: "Find the 6th term of sequence: 1, 4, 9, 16, 25, ...",
              start: 34,
              end: 38,
              precision: 0,
            },
            {
              id: "M27",
              type: "nat",
              question: "If tan θ = 3/4, find sec θ.",
              start: 4,
              end: 6,
              precision: 0,
            },
            {
              id: "M28",
              type: "nat",
              question: "Find the number of diagonals in a pentagon.",
              start: 4,
              end: 6,
              precision: 0,
            },
            {
              id: "M29",
              type: "nat",
              question: "The median of 1, 3, 5, 7, 9, 11, 13 is:",
              start: 6,
              end: 8,
              precision: 0,
            },
            {
              id: "M30",
              type: "nat",
              question: "Find the value of ⁶C₀ + ⁶C₆.",
              start: 1,
              end: 3,
              precision: 0,
            },
          ],
        },
      ],
    },
  ],
};
